- hosts: all
  become: yes
  tasks:
    - name: install git
      apt: name=git state=present
    - name: git clone
      git:
       repo: 'https://github.com/kvswp/mydemo'
       dest: /home/mydemo

